### ISSUE TITLE
gsignond requires suid to create accounts

### ISSUE THREAD

**Issue by quequotion** [alucryd/aur#90]
I initially reported this to elementary OS [against switchboard-plug-online-accounts](https://github.com/elementary/switchboard-plug-onlineaccounts/issues/76), but now I think the problem is with gsignond. Packagers on [Redhat's bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1442547#c3) thought they could patch gsignond not to require suid, as one mentions that elementary OS does, but I don't see any evidence that Redhat ever figured out how.

Edit: elementary OS builds gsignond with `bus_type=session` and `extension=desktop` to make it work with their clients.

**Comment by AdsonCicilioti** [comment]
Do you can't create accounts?

**Comment by alucryd** [comment]
@quequotion Apologies for the huge delay, just added the desktop extension to the [community] gsignon package.
